### ISSUE TITLE
User can see their car 

### ISSUE THREAD

**Issue by codywiseman** [codywiseman/driving-game#2]
## 💰 Motivation

The user needs to see what they will be controlling.

## 📐 Plan

Put a top-down image of a car on the page.

## ✅ Task List

- [x] Pick a background and an image of a car.
- [x]  Apply CSS to create an initial layout of the driving game.
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary.
