### ISSUE TITLE
User can turn their car

### ISSUE THREAD

**Issue by codywiseman** [codywiseman/driving-game#3]
## 💰 Motivation

The user needs to be able to control which way their car is facing.

## 📐 Plan

Rotate the image with CSS classes when the user presses an arrow key.

## ✅ Task List

- [x] Create a CSS rule for each direction of the car.
- [x] Listen for 'keydown' events on the document.
- [x] Create a simple data model that includes which way the car is facing, (north, south, east, or west).
- [x] Car turns in the direction of the arrow key pressed.
- [x] Data model is updated to reflect the new direction the car is facing.
