### ISSUE TITLE
User can steer their car

### ISSUE THREAD

**Issue by codywiseman** [codywiseman/driving-game#6]
## 💰 Motivation

Our game needs MAXIMUM realism to be immersive 😂.

## 📐 Plan

Change the car's location based on which direction it is facing.

## ✅ Task List

- [x] Update startCar function so it updates the carDirection objects x & y axis depending on which direction it is facing.
- [x] startCar function conitnues to run in new direction when direction is changed. 
- [x] Fix all bugs
